name: Maven CI Workflow

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4  

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '11'  
          cache: 'maven'  

      - name: Build the Maven Project
        run: mvn clean install  

      - name: Run Tests
        run: mvn test  
